# Generated by Django 5.2.4 on 2026-07-20 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, help_text="Hex color without '#', e.g. 520102", max_length=8, validators=[django.core.validators.RegexValidator('^[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$')])),
                ('icon_file', models.ImageField(blank=True, null=True, upload_to='music/icons/')),
                ('cover_file', models.ImageField(blank=True, null=True, upload_to='music/covers/')),
                ('icon_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('is_remote', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlists',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Length in seconds')),
                ('thumb_file', models.ImageField(blank=True, null=True, upload_to='music/thumbs/')),
                ('asset_file', models.FileField(blank=True, null=True, upload_to='music/audio/', validators=[django.core.validators.FileExtensionValidator(['opus'])])),
                ('thumb_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('asset_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('is_remote', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='music.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'db_table': 'playlist_songs',
                'ordering': ['position'],
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='music.PlaylistSong', to='music.song'),
        ),
    ]
