# Generated by Django 5.2.4 on 2026-09-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_request_counts',
            },
        ),
    ]
