# Generated by Django 5.2.4 on 2026-07-02 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gym_customuser_gym_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gym',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'gym_owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('gym_owner', 'Gym Owner'), ('trainer', 'Trainer'), ('member', 'Member')], db_index=True, default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(limit_choices_to={'user_type': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE users SET gender = LOWER(gender) WHERE gender IS NOT NULL;
                UPDATE users SET user_type = LOWER(user_type);
                UPDATE users SET status = LOWER(status);
                UPDATE users SET membership_status = LOWER(membership_status) WHERE membership_status IS NOT NULL;
                UPDATE memberships SET payment_mode = LOWER(payment_mode);
                UPDATE memberships SET status = LOWER(status);
                UPDATE payments SET mode = LOWER(mode);
            """,
            reverse_sql="""
                UPDATE users SET gender = UPPER(gender) WHERE gender IS NOT NULL;
                UPDATE users SET user_type = UPPER(user_type);
                UPDATE users SET status = UPPER(status);
                UPDATE users SET membership_status = UPPER(membership_status) WHERE membership_status IS NOT NULL;
                UPDATE memberships SET payment_mode = UPPER(payment_mode);
                UPDATE memberships SET status = UPPER(status);
                UPDATE payments SET mode = UPPER(mode);
            """,
        ),
    ]
