# Generated by Django 5.2.4 on 2026-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_gender_alter_customuser_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trainer_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.RunSQL(
            sql="UPDATE users SET trainer_limit = 5 WHERE user_type = 'gym_owner' AND trainer_limit = 0;",
            reverse_sql="UPDATE users SET trainer_limit = 0 WHERE user_type = 'gym_owner' AND trainer_limit = 5;",
        ),
    ]
