# Generated by Django 5.2.4 on 2026-08-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_payment_paid_by_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
