# Generated by Django 5.2.4 on 2026-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gym_picture',
            field=models.ImageField(blank=True, null=True, upload_to='gym_pictures/'),
        ),
    ]
